### ISSUE TITLE
Liens morts/brisés

### ISSUE THREAD

**Issue by wyslijp16** [mnl-syndicat/website#2]
Sur la page https://mnl-syndicat.fr/communique/1er-mai-dans-la-rue-2023 : 
> [CP_unitaire.original-1Télécharger](https://www.mnl-syndicat.fr/wp-content/uploads/2023/04/CP_unitaire.original-1.png) renvoie 404

Sur la page https://mnl-syndicat.fr/communique/non-fermeture-lycees-idf : 
> [Le 18 octobre dernier](https://www.mnl-syndicat.fr/news/le-18-octobre-cest-greve-et-blocus/) renvoie 500

Sur la page https://mnl-syndicat.fr/communique/retraites-snu-lopmi-non : 
> [Service National Universel](https://www.mnl-syndicat.fr/news/service-national-universel-embrigadement-precarite-refusons-le/) renvoie 500

**Comment by ebanDev** [comment]
Fixé!

**Comment by wyslijp16** [comment]
> Fixé!

Merci beaucoup ! <3
